app = "basaran-demo"
primary_region = "ord"
vm.size = "a100-40gb"

[env]
MODEL="tiiuae/falcon-rw-7b"
#MODEL="huggyllama/llama-7b"
MODEL_CACHE_DIR="/data"
MODEL_TRUST_REMOTE_CODE=true
MODEL_HALF_PRECISION="true"

[build]
image = "hyperonym/basaran:0.19.0"

[[mounts]]
source = "data"
destination = "/data"

[http_service]
internal_port = 80
force_https = true
